collections:
    poetry:
        output: true
        permalink: /:collection/:name/

defaults:
    - scope:
          path: ''
          type: 'poetry'
      values:
          layout: 'poem'
    - scope:
          path: ''
      values:
          layout: 'default'
